pack_directory = "pack/"
output_file_path = "pack/gamula.zip"
skip_pack_icon = false
validate_pack_metadata_file = true
recompress_compressed_files = false
zip_compression_iterations = 32
automatic_minecraft_quirks_detection = false
work_around_minecraft_quirks = [
  "grayscale_images_gamma_miscorrection",
  "java8_zip_parsing",
  "restrictive_banner_layer_texture_format_check",
  "bad_entity_eye_layer_texture_transparency_blending"
]
automatic_asset_types_mask_detection = true
ignore_system_and_hidden_files = true
allow_mods = [ "OptiFine" ]
zip_spec_conformance_level = "balanced"
size_increasing_zip_obfuscation = true
percentage_of_zip_structures_tuned_for_obfuscation_discretion = 100
never_store_squash_times = false

["**/*.{og[ga],mp3,wav,flac}"]
transcode_ogg = true

["**/*.{json,jsonc,mcmeta,mcmetac,jpm,jpmc,jem,jemc,bbmodel,bbmodelc}"]
minify_json = true
delete_bloat_keys = true
always_allow_json_comments = false

["**/*.png"]
image_data_compression_iterations = 16
color_quantization_target = "auto"
color_quantization_dithering_level = 0.85
maximum_width_and_height = 8_192
skip_alpha_optimizations = true

["**/*.{fsh,vsh,glsl}"]
shader_source_transformation_strategy = "keep_as_is"

["**/*.lang"]
minify_legacy_language = true
strip_legacy_language_bom = true

["**/*.mcfunction"]
minify_command_function = true

["**/*.properties"]
minify_properties = true
