name: "Build & Release"
on:  
  push:
    tags: ["**"]

jobs:
  exec:
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Build
      uses: ComunidadAylas/PackSquash-action@v3
      with:
        artifact_name: gamula
        allow_optifine_mod: true
    - name: Fetch
      uses: actions/download-artifact@v3
      with:
        name: gamula
    - name: Rename
      run: mv pack.zip gamula.zip
    - name: Hash
      run: shasum gamula.zip | cut -d " " -f 1 > hash.txt
    - name: Configure Git
      run: git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: gamula.zip,hash.txt
        token: ${{ secrets.GITHUB_TOKEN }}