name: "Build & Release"
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, 'ci-skip:')"
    steps:

# clone
    - name: Clone
      uses: actions/checkout@v3
      with:
        ref: main
        fetch-depth: 0

# shader workaround - prepare
    - name: Shaders Workaround (prepare)
      run: |
        zip -r shaders.zip assets/minecraft/shaders
        rm -r assets/minecraft/shaders

# build -> fetch -> rename
    - name: Build
      uses: ComunidadAylas/PackSquash-action@v4
      with:
        packsquash_version: latest-unstable
        artifact_name: gamula
        options: packsquash_options.toml
    - name: Fetch
      uses: actions/download-artifact@v3
      with:
        name: gamula

# shader workaround - finalize
    - name: Shaders Workaround (finalize)
      run: |
        unzip shaders.zip -d .
        rm shaders.zip
        zip -ur gamula.zip assets/minecraft/shaders

# release
    - name: Hash
      id: hash
      run: |
        HASH=$(shasum gamula.zip | cut -d " " -f 1)
        echo "Exporting pack hash to $HASH"
        echo "pack_hash=$HASH" >> $GITHUB_OUTPUT
    - name: Configure Git
      run: git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"
    - name: Tag & Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}-stable
        target_commitish: main
        files: gamula.zip
        body: |
          **commit:** ${{ github.event.head_commit.message }}
          > hash: ${{ steps.hash.outputs.pack_hash }}
