name: "Build & Release"
on:  
  push:
    tags: ["**"]

jobs:
  exec:
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Build
      uses: ComunidadAylas/PackSquash-action@v3
      with:
        artifact_name: gamula
        allow_optifine_mod: true
        minify_shaders: false
        recompress_compressed_files: true
        zip_spec_conformance_level: disregard
        zip_compression_iterations: 32
        skip_image_alpha_optimizations: true
        size_increasing_zip_obfuscation: true
        percentage_of_zip_structures_tuned_for_obfuscation_discretion: 100
        never_store_squash_times: true
        transcode_ogg: false
        minify_json_files: true
        delete_bloat_json_keys: true
        always_allow_json_comments: false
        image_data_compression_iterations: 16
        image_color_quantization_target: auto
        skip_image_alpha_optimizations: true
        work_around_grayscale_images_gamma_miscorrection_quirk: true
        work_around_java8_zip_parsing_quirk: true
        work_around_restrictive_banner_layer_texture_format_check_quirk: true
        work_around_bad_entity_eye_layer_texture_transparency_blending_quirk: true
        automatic_asset_types_mask_detection: true
    - name: Fetch
      uses: actions/download-artifact@v3
      with:
        name: gamula
    - name: Rename
      run: mv pack.zip gamula.zip
    - name: Hash
      id: hash
      run: |
        HASH=$(shasum gamula.zip | cut -d " " -f 1)
        echo "Exporting pack hash to $HASH"
        echo "pack_hash=$HASH" >> $GITHUB_OUTPUT
    - name: Configure Git
      run: git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: gamula.zip
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          **commit:** ${{ github.event.head_commit.message }}
          > hash: ${{ steps.hash.outputs.pack_hash }}
